In [1]:
import numpy as np
arr2d = np.array([ [1, 2, 3] ,
                   [4, 5, 6] ] )
print(arr2d)


[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6] ,
        [7, 8, 9]
    ]
])

print(arr3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [3]:
import numpy as np
arr3dL = np.array(
[
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]

])

print(arr3dL)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
