<a href="https://colab.research.google.com/github/jaganclt/data-analytics-numpy-pandas-/blob/master/numpy_array_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array(range(1,21))

In [ ]:
arr+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25])

In [ ]:
arr-5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15])

In [ ]:
arr*5

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [ ]:
arr/5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6,
       2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. ])

In [ ]:
np.mean(arr)

10.5

In [ ]:
np.sum(arr)

210

In [ ]:
np.max(arr)

20

In [ ]:
np.min(arr)

1

In [ ]:
arr=np.random.randint(10,50,(4,5))
arr

array([[23, 41, 21, 13, 14],
       [15, 19, 22, 37, 31],
       [32, 30, 42, 40, 28],
       [39, 12, 36, 44, 16]])

In [ ]:
arr[:,3]

array([13, 37, 40, 44])

In [ ]:
arr[:2,:]

array([[23, 41, 21, 13, 14],
       [15, 19, 22, 37, 31]])

In [ ]:
arr[arr>25]=100


In [ ]:
arr

array([[ 23, 100,  21,  13,  14],
       [ 15,  19,  22, 100, 100],
       [100, 100, 100, 100, 100],
       [100,  12, 100, 100,  16]])

In [ ]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
broadcasting

In [4]:
import numpy as np

In [5]:
arr1=np.array([[1],[2],[3]])

In [9]:
arr2=np.array([5,6,7,8])

In [10]:
result = arr1 + arr2
print(result)

[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]]


In [ ]:
statistical functions

In [11]:
import numpy as np

In [15]:
rm_array=np.random.rand(3,3)

In [16]:
m=np.mean(rm_array)
std_deviation=np.std(rm_array)
variance=np.var(rm_array)
print(m)
print(std_deviation)
print(variance)

0.5686179464474537
0.2816807838620972
0.07934406399716554


In [17]:
me=np.median(rm_array,axis=0)
print(me)

[0.77053643 0.4198027  0.20471654]


In [18]:
me=np.median(rm_array,axis=1)
print(me)

[0.26952378 0.86674356 0.68054792]


Sorting and searching

In [21]:
R=np.random.randint(50,101,size=15)
R

array([ 50,  64,  53,  78, 100,  87,  64,  80,  73,  93,  83,  77,  97,
        66,  63])

In [22]:
sorted=np.sort(R)
sorted

array([ 50,  53,  63,  64,  64,  66,  73,  77,  78,  80,  83,  87,  93,
        97, 100])

In [23]:
np.where(sorted>75)

(array([ 7,  8,  9, 10, 11, 12, 13, 14]),)

In [26]:
arr1=np.random.randint(1,11,(3,3))


In [27]:
arr2=np.random.randint(1,11,size=(3,3))

In [28]:
arr1+arr2

array([[14, 13, 19],
       [11,  6, 15],
       [ 8, 10, 14]])

In [29]:
arr1-arr2

array([[-6, -1, -1],
       [-3,  4,  1],
       [ 2,  4,  2]])

In [30]:
arr1*arr2

array([[40, 42, 90],
       [28,  5, 56],
       [15, 21, 48]])

In [31]:
arr1/arr2

array([[0.4       , 0.85714286, 0.9       ],
       [0.57142857, 5.        , 1.14285714],
       [1.66666667, 2.33333333, 1.33333333]])

In [32]:
dot_product=np.dot(arr1,arr2)
dot_product

array([[109,  61, 136],
       [ 99,  57, 123],
       [123,  66, 147]])